### ISSUE TITLE
no train.scp file in training

### ISSUE THREAD

**Issue by Soar-Sir** [smallflyingpig/universal_adversarial_perturbation_generative_network_for_speaker_recognition#1]
Hello, I am interested in your excellent work, but when I  run the code on your md about train model.

`python ./train_generator.py --output_dir ./output/timit_generator --no_dist --noise_scale 1 --norm_factor 1000 --norm_clip 0.01 --speaker_factor 1 --wlen 200 --frame_dim 3200 --margin 10 --data_root ./data/TIMIT  --dataset timit --mul 0.1 --epoch 50  ` 

It was an error on the screen : 

`Namespace(beta=0, data_root='./data/TIMIT', dataset='timit', epoch=50, eval=False, eval_every=-1, frame_dim=3200, local_rank=0, margin=10, mul=0.1, no_dist=True, noise_dim=100, noise_scale=1.0, norm_clip=0.01, norm_factor=1000.0, norm_factor_grow=0, num_workers=8, output_dir='./output/timit_generator', pt_file='none', seed=1234, speaker_cfg='./config/timit_speaker_generator.cfg', speaker_factor=1.0, speaker_model='./output/SincNet_TIMIT/model_raw.pkl', target=-1, test=False, test_interpolation=False, test_output='./output/timit_generator_test', wlen=200)
read config file:  ./config/timit_speaker_generator.cfg
set seed:  1234
load data list file from:  ./data/TIMIT/processed/train.scp
Traceback (most recent call last):
  File "./train_generator.py", line 731, in <module>
    main(args)
  File "./train_generator.py", line 631, in main
    train_dataset = TIMIT_speaker_norm(args.data_root, train=True, wlen=args.wlen, phoneme=False, norm_factor=True, augment=False)
  File "/home/soar/adversarial/UAP/common/dataset.py", line 210, in __init__
    self.data = read_list(data_list_file)
  File "/home/soar/adversarial/UAP/common/dataset.py", line 16, in read_list
    with open(filename, "r") as fp:
FileNotFoundError: [Errno 2] No such file or directory: './data/TIMIT/processed/train.scp'`

I check the code, and I can't find the train.scp file, so can you update the project?

It is very helpful to me, thanks a lot!

**Comment by smallflyingpig** [comment]
Hi, I am sorry that I just notice your question. The data list file comes from SincNet(https://github.com/mravanelli/SincNet), I will update the project and add the scp files as soon as possible.

**Comment by BecauseY** [comment]
Please update the project

**Comment by smallflyingpig** [comment]
> Please update the project

Hi, I have uploaded the file (train.scp). I will close this issue.
